# Default values for fluentd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: gcr.io/stackdriver-agents/stackdriver-logging-agent:0.6-1.6.0-1
project_id: pci-poc-management
