# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  _GOOGLE_GROUPS_DOMAIN: ''
  _TF_ADMIN_BUCKET: ''
  _TF_ADMIN_PROJECT: ''
  _TF_VAR_BILLING_ACCOUNT: ''
  _TF_VAR_FOLDER_ID: ''
  _TF_VAR_FRONTEND_ZONE_DNS_NAME: ''
  _TF_VAR_GSUITE_ID: ''
  _TF_VAR_ORG_ID: ''
  _TF_VAR_PROJECT_PREFIX: ''
  _GOOGLE_APPLICATION_CREDENTIALS: ''
  
timeout: 3000s
steps:
- id: 'Build Infra'
  name: 'gcr.io/cloud-foundation-cicd/cft/developer-tools:0'
  waitFor: ['-']
  entrypoint: 'sh'
  env:
  - GOOGLE_GROUPS_DOMAIN=${_GOOGLE_GROUPS_DOMAIN}
  - TF_ADMIN_BUCKET=${_TF_ADMIN_BUCKET}
  - TF_ADMIN_PROJECT=${_TF_ADMIN_PROJECT}
  - TF_VAR_billing_account=${_TF_VAR_BILLING_ACCOUNT}
  - TF_VAR_folder_id=${_TF_VAR_FOLDER_ID}
  - TF_VAR_frontend_zone_dns_name=${_TF_VAR_FRONTEND_ZONE_DNS_NAME}
  - TF_VAR_gsuite_id=${_TF_VAR_GSUITE_ID}
  - TF_VAR_org_id=${_TF_VAR_ORG_ID}
  - TF_VAR_project_prefix=${_TF_VAR_PROJECT_PREFIX}
  args: 
  - '-c'
  - |
      cp workstation.env.example workstation.env
      sed -i "s/YOUR_ORG_ID/${_TF_VAR_ORG_ID}/g" workstation.env
      sed -i "s/YOUR_GSUITE_ID/${_TF_VAR_GSUITE_ID}/g" workstation.env
      sed -i "s/YOUR_BILLING_ACCOUNT_ID/${_TF_VAR_BILLING_ACCOUNT}/g" workstation.env
      sed -i "s/YOUR_PROJECT_FOLDER/${_TF_VAR_FOLDER_ID}/g" workstation.env
      sed -i "s/demo-pci/${_TF_VAR_PROJECT_PREFIX}/g" workstation.env
      sed -i "/export TF_ADMIN_PROJECT/c\export TF_ADMIN_PROJECT=${_TF_ADMIN_PROJECT}" workstation.env
      sed -i "s/terraform-admin-<INSERT-RANDOM-IDENTIFIER-HERE>/${_TF_ADMIN_BUCKET}/g" workstation.env
      sed -i "/GOOGLE_APPLICATION_CREDENTIALS=/c\export GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}" workstation.env
      sed -i "/TF_VAR_frontend_zone_dns_name=/c\export TF_VAR_frontend_zone_dns_name=\"${_TF_VAR_FRONTEND_ZONE_DNS_NAME}\"" workstation.env
      sed -i "/GOOGLE_GROUPS_DOMAIN=/c\GOOGLE_GROUPS_DOMAIN=\"${_GOOGLE_GROUPS_DOMAIN}\"" workstation.env
      cat workstation.env
      source workstation.env
      ./_helpers/build-infra.sh
