apiVersion: v1
appVersion: "1.0"
description: |
  A Helm chart to deploy a customized fluentd Daemonset that uses GCP's DLP API
  to redact credit card numbers from logs sent to Stackdriver Logging.
  Additionally, logs are sent to a custom project via the project_id setting.
name: fluentd-filter-dlp
version: 0.1.0
