apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sender
spec:
  selector:
    matchLabels:
      app: nginx-sender
  template:
    metadata:
      labels:
        app: nginx-sender
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
       - name: nginx-config
         configMap:
           name: nginx-config-sender
       - name: ssl
         secret:
           secretName: tls-hipsterservice
      containers:
      - name: nginx
        image: nginx:1.14.2
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-ssl
          mountPath: /etc/nginx/ssl
          name: ssl
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sender
spec:
  type: ClusterIP
  selector:
    app: nginx-sender
  ports:
  - name: productcatalogservice
    port: 3550
    targetPort: 3550
  - name: currencyservice
    port: 7000
    targetPort: 7000
  - name: cartservice
    port: 7070
    targetPort: 7070
  - name: recommendationservice
    port: 8080
    targetPort: 8080
  - name: shippingservice
    port: 50051
    targetPort: 50051
  - name: adservice
    port: 9555
    targetPort: 9555
  - name: emailservice
    port: 5000
    targetPort: 5000
